skip deploying client to s3 now that everything is on cloudflare

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -195,52 +195,52 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
-      - name: Update deployment
-        working-directory: ./packages/client
-        env:
-          S3_BUCKET: ${{ secrets.S3_CLIENT_BUCKET}}
-        run: |
-          ls -l
-          if [[ -z "$S3_BUCKET" ]]; then
-            echo "S3_BUCKET could not be found" 1>&2
-            exit 1
-          fi
+      # - name: Update deployment
+      #   working-directory: ./packages/client
+      #   env:
+      #     S3_BUCKET: ${{ secrets.S3_CLIENT_BUCKET}}
+      #   run: |
+      #     ls -l
+      #     if [[ -z "$S3_BUCKET" ]]; then
+      #       echo "S3_BUCKET could not be found" 1>&2
+      #       exit 1
+      #     fi
 
-          echo "Uploading files to $S3_BUCKET..."
-          aws s3 sync build $S3_BUCKET \
-            --acl public-read \
-            --cache-control max-age=31536000 \
-            --exclude service-worker.js \
-            --exclude manifest.json \
-            --exclude index.html \
-            --delete
+      #     echo "Uploading files to $S3_BUCKET..."
+      #     aws s3 sync build $S3_BUCKET \
+      #       --acl public-read \
+      #       --cache-control max-age=31536000 \
+      #       --exclude service-worker.js \
+      #       --exclude manifest.json \
+      #       --exclude index.html \
+      #       --delete
 
-          echo "Uploading manifest.json"
-          aws s3 cp build/manifest.json $S3_BUCKET/manifest.json \
-            --metadata-directive REPLACE \
-            --cache-control max-age=0,no-cache,no-store,must-revalidate \
-            --content-type application/json \
-            --acl public-read
+      #     echo "Uploading manifest.json"
+      #     aws s3 cp build/manifest.json $S3_BUCKET/manifest.json \
+      #       --metadata-directive REPLACE \
+      #       --cache-control max-age=0,no-cache,no-store,must-revalidate \
+      #       --content-type application/json \
+      #       --acl public-read
 
-          echo "Uploading index.html"
-          aws s3 cp build/index.html $S3_BUCKET/index.html \
-            --metadata-directive REPLACE \
-            --cache-control max-age=0,no-cache,no-store,must-revalidate \
-            --content-type text/html \
-            --acl public-read
+      #     echo "Uploading index.html"
+      #     aws s3 cp build/index.html $S3_BUCKET/index.html \
+      #       --metadata-directive REPLACE \
+      #       --cache-control max-age=0,no-cache,no-store,must-revalidate \
+      #       --content-type text/html \
+      #       --acl public-read
 
-          echo "Uploading service-worker.js"
-          aws s3 cp build/service-worker.js $S3_BUCKET/service-worker.js \
-            --metadata-directive REPLACE \
-            --cache-control max-age=300 \
-            --content-type text/javascript \
-            --acl public-read
+      #     echo "Uploading service-worker.js"
+      #     aws s3 cp build/service-worker.js $S3_BUCKET/service-worker.js \
+      #       --metadata-directive REPLACE \
+      #       --cache-control max-age=300 \
+      #       --content-type text/javascript \
+      #       --acl public-read
 
-          aws s3 cp build/service-worker.js.map $S3_BUCKET/service-worker.js.map \
-            --metadata-directive REPLACE \
-            --cache-control max-age=300 \
-            --content-type text/javascript \
-            --acl public-read
+      #     aws s3 cp build/service-worker.js.map $S3_BUCKET/service-worker.js.map \
+      #       --metadata-directive REPLACE \
+      #       --cache-control max-age=300 \
+      #       --content-type text/javascript \
+      #       --acl public-read
       - name: deploy to cloudflare pages
         id: wrangler
         working-directory: ./packages/client
