Fixing actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -131,6 +131,11 @@ jobs:
           SKIP_PREFLIGHT_CHECK: true
         run: |
           npm run build
+      - name: Store build artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: client-build
+          path: build
   run-migrations:
     name: Run Database Migrations
     runs-on: ubuntu-latest
@@ -158,9 +163,44 @@ jobs:
       - test-client
       - build-client
     steps:
+      - name: Download client build artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: client-build
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
+      - name: Update deployment
+        env:
+          S3_BUCKET: ${{ secrets.S3_CLIENT_BUCKET}}
+        run: |
+          if [[ -z "$S3_BUCKET" ]]; then
+            echo "S3_BUCKET could not be found" 1>&2
+            exit 1
+          fi
+
+          echo "Uploading files to $S3_BUCKET..."
+          aws s3 sync build $S3_BUCKET \
+            --acl public-read \
+            --cache-control max-age=31536000 \
+            --exclude service-worker.js \
+            --exclude manifest.json \
+            --exclude index.html \
+            --delete
+
+          echo "Uploading manifest.json"
+          aws s3 cp build/manifest.json $S3_BUCKET/manifest.json \
+            --metadata-directive REPLACE \
+            --cache-control max-age=0,no-cache,no-store,must-revalidate \
+            --content-type application/json \
+            --acl public-read
+
+          echo "Uploading index.html"
+          aws s3 cp build/index.html $S3_BUCKET/index.html \
+            --metadata-directive REPLACE \
+            --cache-control max-age=0,no-cache,no-store,must-revalidate \
+            --content-type text/html \
+            --acl public-read
